#ifndef __language_ch_h
#define __language_ch_h

/* Chino simplificado del LCD. La fuente dlc32Font solo trae estos caracteres chinos:
 * (131 glifos), asi que algunos textos usan sinonimos con ellos (速率 en vez de 速度) y los que
 * no se pueden escribir se dejan en ingles (Spindle, Cooling). */

#define BACK_CH                        "返回"
#define YES_CH                         "是"
#define NO_CH                          "否"
#define CONTROL_CH                     "控制"
#define SCULPTURE_CH                   "雕刻"
#define TOOL_CH                        "工具"
#define MPOS_CH                        "机器位置"
#define WPOS_CH                        "工件位置"
#define WIFI_CONNECT_CH                "连接"
#define WIFI_DISCONNECT_CH             "断开"
#define XY_CLEAR_CH                    "XY零点"
#define Z_CLEAR_CH                     "Z零点"
#define KNIFE_CH                       "刻具"
#define NEXT_CH                        "下一页"
#define UP_CH                          "上一页"
#define COOLING_CH                     "Cooling"
#define POSITION_CH                    "位置"
#define SPEED_HIGH_CH                  "高速"
#define SPEED_MID_CH                   "中速"
#define SPEED_LOW_CH                   "低速"
#define SPINDLE_CH                     "Spindle"
#define CARVE_CH                       "雕刻"
#define DIS_NO_SDCARD_CH               "无SD卡"
#define HOLD_CH                        "暂停"
#define CYCLE_CH                       "雕刻"
#define STOP_CH                        "停止"
#define ADJUST_CH                      "调整"
#define SPINDLE_SPPED_CH               "Spindle:"
#define FEED_RATE_CH                   "速率:"
#define RAPID_SPEED_CH                 "高速"
#define CARVE_TIMES_CH                 "times:"
#define DIS_STOP_CARVE_CH              "是否停止雕刻?"
#define DIS_HOMEING_CH                 "回零中..."
#define DIS_NO_HARD_HOME_CH            "硬限位未开"
#define DIS_HOME_SUCCEED_CH            "回零成功"
#define DIS_HOME_FAIL_CH               "回零失败"
#define DIS_PROBE_SECCEED_CH           "检测成功"
#define DIS_PROBE_FAIL_CH              "检测失败"
#define DIS_HARD_LIMIT_CH              "硬限位!"
#define DIS_SOFT_LIMIT_CH              "超过边界!"
#define CANCEL_CH                      "取消"
#define FRAME_CH                       "巡边"
#define CARVE_FILE_SURE_CH             "是否雕刻文件?"
#define PAUSE_CH                       "暂停"
#define START_CH                       "雕刻"
#define CONFIRM_CH                     "确认"
#define ADD_CH                         "+"
#define REDUCE_CH                      "-"
#define EXIT_CH                        "关闭"
#define LANGUAGE_CH                    "语言"
#define SCANF_CH                       "扫描"
#define RECONNECT_CH                   "重连"
#define CONNECT_CH                     "连接"
#define PASSWORD_CH                    "密码:"
#define Z_HOME_CH                      "Z回零"
#define UPDATE_TITLE_CH                "固件..."
#define INFO_CH                        "信息"
#define WARNING_CH                     "警告"
#define ERROR_CH                       "错误"
#define UNLOCK_SUCCESS_CH              "解锁成功!"
#define SETTING_ERROR_CH               "设置错误!"
#define SET_6_1_CH                     "请设置$6=1!"
#define WAIT_IDLE_CH                   "请等待机器停止"
#define FILE_TOO_BIG_CH                "文件超过限制"
#define CONTINUE_SURE_CH               "是否继续?"
#define FILE_LOADING_CH                "正在读取文件"
#define LOADING_FILE_CH                "正在读取文件..."
#define SD_BUSY_CH                     "SD卡读取中..."
#define RUNNING_CH                     "雕刻中..."
#define PRINT_STOP_SURE_CH             "是否停止雕刻?"
#define PRINT_DONE_CH                  "雕刻完成!"
#define WIFI_SCANNING_CH               "扫描Wifi..."
#define WIFI_CONNECTING_CH             "连接Wifi中..."
#define WIFI_DISCONNECTING_CH          "断开Wifi中..."
#define WIFI_PWD_PROMPT_CH             "密码:"
#define WIFI_STATUS_ON_CH              "WIFI:已连接"
#define WIFI_STATUS_OFF_CH             "WIFI:未连接"
#define UPDATE_SUCCEED_CH              "完成"
#define UPDATE_RESTART_CH              "请重新开机"
#define UPDATE_FAIL_CH                 "失败"
#define UPDATE_FAIL_HELP_CH            "请检测SD卡"
#define POWER_FMT_CH                   "功率:%d%%"
#define SPEED_FMT_CH                   "速率:%d%%"
#define SPINDLE_SPEED_FMT_CH           "Spindle: %d%%"
#define FEED_RATE_FMT_CH               "速率: %d%%"
#define RAPID_FMT_CH                   "高速: %d%%"
#define GAUGE_FEED_CH                  "速率"
#define GAUGE_SPINDLE_CH               "Spindle"
#define GAUGE_RAPID_CH                 "高速"
#define JOB_ELAPSED_CH                 "已用"
#define JOB_LEFT_CH                    "待完成"
#define JOB_FEED_REAL_CH               "速率"
#define JOB_POWER_REAL_CH              "功率"
#define RESUME_CH                      "继续"
#define TOOL_BOARD_CH                  "主板"
#define SPINDLE_LASER_CH               "激光"
#define SPINDLE_SPEED_LASER_CH         "激光功率:"
#define SPINDLE_SPEED_FMT_LASER_CH     "功率: %d%%"
#define GAUGE_SPINDLE_LASER_CH         "功率"
#define FEED_RATE_LASER_CH             "速率:"
#define FEED_RATE_FMT_LASER_CH         "速率: %d%%"
#define GAUGE_FEED_LASER_CH            "速率"
#define JOB_FEED_REAL_LASER_CH         "速率"
#define TESTING_CH                     "检测中..."
#define PROBE_CHECK_CH                 "检测:"
#define X_LIMIT_CHECK_CH               "X限位检测:"
#define Y_LIMIT_CHECK_CH               "Y限位检测:"
#define Z_LIMIT_CHECK_CH               "Z限位检测:"
#define SD_CHECK_CH                    "SD卡检测:OK"
#define I2C_CHECK_CH                   "I2C检测:"
#define CPU_TEMP_CH                    "CPU:"
#define TEST_WARNING_CH                "#FF0000 警告!#"

#endif
