#ifndef __language_en_h
#define __language_en_h

/* 公共 */
#define BACK_EN                 "Back"
#define YES_EN                  "Yes"
#define NO_EN                   "No"

/* 主页 */
#define CONTROL_EN              "Control"           
#define SCULPTURE_EN            "Sculpture"         
#define TOOL_EN                 "Tool"          
#define MPOS_EN                 "Mechanical"          
#define WPOS_EN                 "Working"
#define WIFI_CONNECT_EN   	    "Connect"
#define WIFI_DISCONNECT_EN	    "Disconnect"

/* 控制界面 */
#define XY_CLEAR_EN             "XY_Clear"
#define Z_CLEAR_EN              "Z_Clear"
#define KNIFE_EN                "Knife"
#define NEXT_EN                 "Next"
#define UP_EN                   "Up"
#define COOLING_EN              "Cooling"
#define POSITION_EN             "Position"
#define SPEED_HIGH_EN           "High Speed"
#define SPEED_MID_EN            "Mid Speed"
#define SPEED_LOW_EN            "Low Speed"
#define SPINDLE_EN              "Spindle"
#define CARVE_EN                "Carve"

/* 文件界面 */
#define DIS_NO_SDCARD_EN        "No SD Card"

/* 雕刻界面 */
#define HOLD_EN                 "Hold"
#define CYCLE_EN                "Cycle"
#define STOP_EN                 "Stop"
#define ADJUST_EN               "Adjustment"
#define SPINDLE_SPPED_EN        "Spindle speed:"
#define FEED_RATE_EN            "Feed rate:"
#define RAPID_SPEED_EN          "Rapid speed"
#define CARVE_TIMES_EN          "time:"

/* 提示 */
#define DIS_STOP_CARVE_EN 		"Do you want to stop carve?"
#define DIS_HOMEING_EN    		"Homing..."
#define DIS_NO_HARD_HOME_EN  	"No Enable Hard Homing..."
#define DIS_HOME_SUCCEED_EN  	"Homing succeed!"
#define DIS_HOME_FAIL_EN    	"Homing fail"
#define DIS_PROBE_SET           "Setting probe..."
#define DIS_PROBE_SECCEED_EN    "Probe succeed!"
#define DIS_PROBE_FAIL_EN       "Probe fail!"
#define DIS_HARD_LIMIT_EN       "Hard Limit!"
#define DIS_SOFT_LIMIT_EN       "Soft Limit!"
#define DIS_UNLOCK              "please unlock!"
#define DIS_WAIT_MC_STOP        "Please wait machine stop!"
#define DIS_POS_SUCCEED         "Positioning success"

/* Botones y popups (antes literales fijos en el codigo de cada pagina) */
#define CANCEL_EN               "Cancel"
#define FRAME_EN                "Frame"
#define CARVE_FILE_SURE_EN      "Is Caving this File?"
#define PAUSE_EN                "Pause"
#define START_EN                "Start"
#define CONFIRM_EN              "Confirm"
#define ADD_EN                  "Add"
#define REDUCE_EN               "Reduce"
#define EXIT_EN                 "Exit"
#define LANGUAGE_EN             "Language"
#define SCANF_EN                "Scan"
#define RECONNECT_EN            "Reconnect"
#define CONNECT_EN              "Connect"
#define PASSWORD_EN             "Password:"
#define Z_HOME_EN               "Z Home"
#define UPDATE_TITLE_EN         "Update..."

/* Avisos y mensajes de dialogo */
#define INFO_EN                 "Info"
#define WARNING_EN              "Warning"
#define ERROR_EN                "Error"
#define UNLOCK_SUCCESS_EN       "Unlock success!"
#define SETTING_ERROR_EN        "Setting error!"
#define SET_6_1_EN              "Please set $6=1!"
#define WAIT_IDLE_EN            "Please wait machine idle!"
#define FILE_TOO_BIG_EN         "File size is too big"
#define CONTINUE_SURE_EN        "Do you want to continue?"
#define FILE_LOADING_EN         "File is Loading"
#define LOADING_FILE_EN         "Loading File..."
#define SD_BUSY_EN              "SD is busy..."
#define RUNNING_EN              "Running..."
#define PRINT_STOP_SURE_EN      "Do you want to stop print?"
#define PRINT_DONE_EN           "File is print done!"
#define WIFI_SCANNING_EN        "Scanning wifi..."
#define WIFI_CONNECTING_EN      "Connecting wifi..."
#define WIFI_DISCONNECTING_EN   "Disconnecting wifi..."
#define WIFI_PWD_PROMPT_EN      "Please enter password to connect"
#define WIFI_STATUS_ON_EN       "WIFI:Connect"
#define WIFI_STATUS_OFF_EN      "WIFI:Disconnect"
#define UPDATE_SUCCEED_EN       "Update succeed"
#define UPDATE_RESTART_EN       "Please restart!"
#define UPDATE_FAIL_EN          "Update Fail"
#define UPDATE_FAIL_HELP_EN     "Please Check mkscfg.txt or sdcard"

/* Formatos con %d */
#define POWER_FMT_EN            "Power:%d%%"
#define SPEED_FMT_EN            "Speed:%d%%"
#define SPINDLE_SPEED_FMT_EN    "Spindle speed: %d%%"
#define FEED_RATE_FMT_EN        "Feed rate: %d%%"
#define RAPID_FMT_EN            "Rapid speed: %d%%"
#define GAUGE_FEED_EN            "Feed"
#define GAUGE_SPINDLE_EN         "Spindle"
#define GAUGE_RAPID_EN           "Rapid"
#define JOB_ELAPSED_EN           "Elapsed"
#define JOB_LEFT_EN              "Left"
#define JOB_FEED_REAL_EN         "Feed"
#define JOB_POWER_REAL_EN        "Power"
#define RESUME_EN                "Resume"
#define TOOL_BOARD_EN            "Board"
// Rotulos con el modo laser activo ($32=1): potencia y velocidad en vez de husillo y avance
#define SPINDLE_LASER_EN               "Laser"
#define SPINDLE_SPEED_LASER_EN         "Laser power:"
#define SPINDLE_SPEED_FMT_LASER_EN     "Power: %d%%"
#define GAUGE_SPINDLE_LASER_EN         "Power"
#define FEED_RATE_LASER_EN             "Speed:"
#define FEED_RATE_FMT_LASER_EN         "Speed: %d%%"
#define GAUGE_FEED_LASER_EN            "Speed"
#define JOB_FEED_REAL_LASER_EN         "Speed"

/* Pagina de pruebas (test) */
#define TESTING_EN              "Testing..."
#define PROBE_CHECK_EN          "Probe Check:"
#define X_LIMIT_CHECK_EN        "X_limit Check:"
#define Y_LIMIT_CHECK_EN        "Y_limit Check:"
#define Z_LIMIT_CHECK_EN        "Z_limit Check:"
#define SD_CHECK_EN             "SD Check:OK"
#define I2C_CHECK_EN            "I2C Check:"
#define CPU_TEMP_EN             "CPU_TEMP:"
#define TEST_WARNING_EN         "#FF0000 Warning!#"

#endif
